language: python
jobs:
  include:
    - name: "Python 3.8.0 on Bionic Linux"
      dist: bionic
      python: 3.8
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2            # Python 3.7.4 running on macOS 10.14.4
      language: shell
    - name: "Python 3.8.0 on Windows"
      os: windows                     # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install -e .
script:
  - echo "Hello Travis"
  - npm install
  - npm run lint
  - python3 --version || python --version
  - pytest